import React, { useState, useEffect } from 'react';
import * as XLSX from 'xlsx';

// Use environment variable in production, fallback to local Flask server for dev
const API_BASE = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:5000/api';

export default function App() {
  const [isDark, setIsDark] = useState(true);
  const [showSettings, setShowSettings] = useState(false);
  const [showPreviewModal, setShowPreviewModal] = useState(false);

  // Active User Interface Module
  const [activeModule, setActiveModule] = useState('testplan'); // 'testplan' or 'testcases'

  // Connection settings states
  const [llmConfig, setLlmConfig] = useState({ provider: 'openai', apiUrl: '', apiKey: '', modelName: '' });
  const [sourceConfig, setSourceConfig] = useState({ provider: 'jira', domainUrl: '', email: '', apiToken: '' });

  // Input states
  const [sourceMode, setSourceMode] = useState('text'); // 'text', 'jira', or 'testplan'
  const [jiraKey, setJiraKey] = useState('');
  const [inputText, setInputText] = useState('');
  
  // Cross-module states
  const [generatedTestPlanRef, setGeneratedTestPlanRef] = useState(''); // Stores the last text generated by the plan tool

  // UI Feedback states
  const [jiraFetchStatus, setJiraFetchStatus] = useState(false);
  const [ticketContext, setTicketContext] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedOutput, setGeneratedOutput] = useState(null);

  const [llmTestStatus, setLlmTestStatus] = useState('');
  const [jiraTestStatus, setJiraTestStatus] = useState('');

  // History State
  const [history, setHistory] = useState([]);

  useEffect(() => {
    document.documentElement.classList.toggle('dark', isDark);
  }, [isDark]);

  const handleModuleSwitch = (mod) => {
    setActiveModule(mod);
    
    // In Test Cases module, enable testplan context if we have one
    if (mod === 'testcases' && generatedOutput && activeModule === 'testplan') {
       // Save off the current Test Plan output right before transitioning
       setGeneratedTestPlanRef(generatedOutput);
       setSourceMode('testplan');
    } else {
       setSourceMode('text');
    }

    setGeneratedOutput(null);
    setTicketContext('');
  };

  const testConnection = async (uiType) => {
    const setStatus = uiType === 'llm' ? setLlmTestStatus : setJiraTestStatus;
    setStatus('checking');
    
    try {
      const backendType = uiType === 'jira' ? 'source' : uiType;
      const payload = {
        type: backendType, 
        config: uiType === 'llm' ? 
          { provider: llmConfig.provider, api_url: llmConfig.apiUrl, api_key: llmConfig.apiKey, model_name: llmConfig.modelName } :
          { provider: sourceConfig.provider, domain_url: sourceConfig.domainUrl, email: sourceConfig.email, api_token: sourceConfig.apiToken }
      };

      const res = await fetch(`${API_BASE}/test_connection`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      
      setStatus(data.status === 'success' ? 'success' : 'error');
      if (data.status === 'error') {
         alert(data.message);
      } else {
         setTimeout(() => setStatus(''), 3000);
      }
    } catch (e) {
      console.error(e);
      setStatus('error');
    }
  };

  const fetchJiraTicket = async () => {
    if (!jiraKey.trim()) return;
    setJiraFetchStatus(true);
    setTicketContext('');
    
    try {
      const payload = {
        source_config: { provider: sourceConfig.provider, domain_url: sourceConfig.domainUrl, email: sourceConfig.email, api_token: sourceConfig.apiToken },
        request_data: { ticket_id: jiraKey }
      };

      const res = await fetch(`${API_BASE}/fetch_ticket`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      
      if (data.status === 'success') {
         setTicketContext(data.ticket_context);
      } else {
         setTicketContext(`Error: ${data.message}\nMake sure your Jira credentials in settings are correct.`);
      }
    } catch (e) {
      setTicketContext("Network error fetching ticket.");
    } finally {
      setJiraFetchStatus(false);
    }
  };

  const executeAIRequest = async () => {
    setIsGenerating(true);
    setGeneratedOutput('');
    
    // Determine the context to send depending on the source mode
    let combinedContext = '';
    if (sourceMode === 'testplan') {
       combinedContext = `Previous Test Plan Payload:\n${generatedTestPlanRef}\n\nAdditional Notes: ${inputText}`;
    } else if (sourceMode === 'jira') {
       combinedContext = `Jira Ticket Output:\n${ticketContext}\n\nAdditional Notes: ${inputText}`;
    } else {
       combinedContext = `Requirements:\n${inputText}`;
    }

    const payload = {
      llm_config: { provider: llmConfig.provider, api_url: llmConfig.apiUrl, api_key: llmConfig.apiKey, model_name: llmConfig.modelName },
      source_config: { provider: sourceConfig.provider, domain_url: sourceConfig.domainUrl, email: sourceConfig.email, api_token: sourceConfig.apiToken },
      request_data: { 
         ticket_id: sourceMode === 'jira' ? jiraKey : '', 
         additional_context: combinedContext,
         attachments: [] 
      }
    };

    const endpoint = activeModule === 'testplan' ? '/generate_plan' : '/generate_cases';

    try {
      const res = await fetch(`${API_BASE}${endpoint}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      
      const contentType = res.headers.get('content-type') || '';
      if (contentType.includes('application/json')) {
         const data = await res.json();
         if (data.status === 'success') {
             setGeneratedOutput(data.data?.generated_plan_text || data.data);
         } else {
             setGeneratedOutput(`Generation Error: ${data.message}`);
         }
      } else {
         // SSE stream native consumption
         const reader = res.body.getReader();
         const decoder = new TextDecoder('utf-8');
         let finalOutput = '';
         
         while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            
            const chunk = decoder.decode(value, { stream: true });
            const lines = chunk.split('\n');
            
            for (let line of lines) {
                line = line.trim();
                if (line.startsWith('data: ')) {
                    const dataStr = line.replace('data: ', '').trim();
                    if (dataStr === '[DONE]') continue;
                    try {
                        const parsed = JSON.parse(dataStr);
                        const token = parsed.choices?.[0]?.delta?.content || "";
                        if (token) {
                            finalOutput += token;
                            setGeneratedOutput(finalOutput);
                        }
                    } catch (e) {}
                }
            }
         }
         
         // Format History Tagging
         let rawTitle = sourceMode === 'jira' && jiraKey ? `Jira: ${jiraKey}` : (sourceMode === 'testplan' ? 'From Test Plan' : (inputText ? inputText : 'Blank Context'));
         let cleanTitle = rawTitle.length > 25 ? rawTitle.substring(0, 25) + "..." : rawTitle;

         const newEntry = {
            id: Date.now(),
            title: `${activeModule === 'testplan' ? 'Plan' : 'Cases'} | ${cleanTitle}`,
            timestamp: new Date().toLocaleString([], { dateStyle: 'short', timeStyle: 'short' }),
            sourceMode,
            activeModule,
            jiraKey,
            inputText,
            ticketContext,
            generatedOutput: finalOutput
         };
         setHistory(prev => [newEntry, ...prev]);
         
         // If we generated a test plan, sync it so cases can consume it later
         if (activeModule === 'testplan') setGeneratedTestPlanRef(finalOutput);
      }
    } catch (e) {
      setGeneratedOutput("Network connection error. Ensure the API/Edge architecture is correctly mapped.");
    } finally {
      setIsGenerating(false);
    }
  };

  const loadHistoryItem = (entry) => {
     setActiveModule(entry.activeModule || 'testplan');
     setSourceMode(entry.sourceMode);
     setJiraKey(entry.jiraKey);
     setInputText(entry.inputText);
     setTicketContext(entry.ticketContext);
     setGeneratedOutput(entry.generatedOutput);
  };

  const downloadMarkdown = (contentToDownload = null) => {
    const textToSave = contentToDownload || generatedOutput;
    if (!textToSave) return alert("Nothing to download!");
    const blob = new Blob([textToSave], {type: 'text/markdown'});
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `GenTools_${activeModule}_${Date.now()}.md`;
    a.click();
  };

  const downloadXLSX = (contentToDownload = null) => {
    const textToSave = contentToDownload || generatedOutput;
    if (!textToSave) return alert("Nothing to download!");
    
    const lines = textToSave.split('\n');
    const tableLines = lines.filter(l => l.trim().startsWith('|'));
    
    if (tableLines.length < 2) {
       return alert("No Markdown tabular structure detected. Expected strict Test Case table columns.");
    }
    
    const data = [];
    tableLines.forEach((line) => {
       if (line.includes('---')) return; // Skip divider row
       let row = line.split('|').map(cell => cell.trim());
       row = row.slice(1, -1); // strip leading and trailing empty elements caused by borders
       data.push(row);
    });
    
    const sheet = XLSX.utils.aoa_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, sheet, "TestCases");
    XLSX.writeFile(workbook, `SmartTestCases_${Date.now()}.xlsx`);
  };

  const extractMarkdownTable = (text) => {
    if (!text) return "No test cases generated yet.";
    const lines = text.split('\n');
    const tableLines = lines.filter(l => l.trim().startsWith('|'));
    if (tableLines.length === 0) return "No tabular test cases found in the output.";
    return tableLines.join('\n');
  };

  const parseMarkdownToTable = (text) => {
    if (!text) return null;
    const lines = text.split('\n').filter(l => l.trim().startsWith('|'));
    if (lines.length === 0) return <p className="text-slate-400 italic text-sm">No table found in the generated output.</p>;

    const rows = lines
      .filter(l => !l.match(/^[|\s:-]+$/))
      .map(line => line.split('|').map(c => c.trim()).filter((_, i, arr) => i > 0 && i < arr.length - 1));

    if (rows.length === 0) return null;
    const [headers, ...bodyRows] = rows;

    return (
      <div className="overflow-x-auto w-full">
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className={isDark ? 'bg-slate-700/60' : 'bg-slate-100'}>
              {headers.map((h, i) => (
                <th key={i} className={`px-4 py-3 text-left font-bold text-xs uppercase tracking-wider border ${isDark ? 'border-slate-600 text-slate-200' : 'border-slate-300 text-slate-700'}`}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {bodyRows.map((row, ri) => (
              <tr key={ri} className={ri % 2 === 0 ? (isDark ? 'bg-slate-800/30' : 'bg-white') : (isDark ? 'bg-slate-800/60' : 'bg-slate-50')}>
                {headers.map((_, ci) => (
                  <td key={ci} className={`px-4 py-3 align-top border text-sm leading-relaxed ${isDark ? 'border-slate-700 text-slate-300' : 'border-slate-200 text-slate-700'} ${ci === 0 ? 'font-mono font-bold text-blue-500 whitespace-nowrap' : ''}`}>
                    {row[ci] || ''}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  };

  return (
    <div className={`h-screen flex transition-colors duration-300 overflow-hidden font-sans ${isDark ? 'dark bg-[#0f172a] text-slate-100' : 'bg-slate-50 text-slate-900'}`}>
      <aside className={`w-72 border-r flex flex-col shrink-0 ${isDark ? 'bg-[#1e293b] border-[#334155]' : 'bg-white border-slate-200'}`}>
        <div className={`p-4 border-b flex items-center gap-3 shrink-0 ${isDark ? 'border-[#334155]' : 'border-slate-200'}`}>
          <div className="bg-blue-600 p-2 rounded-lg text-white">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 002-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" /></svg>
          </div>
          <span className="text-xl font-bold tracking-tight">GenTools <span className="text-blue-500">AI</span></span>
        </div>
        
        <nav className="p-4 space-y-3 shrink-0">
          <p className="px-2 text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">Modules</p>
          <button onClick={() => handleModuleSwitch('testplan')} className={`w-full flex items-center gap-3 p-3 text-sm font-semibold rounded-xl border transition-all ${activeModule === 'testplan' ? 'bg-blue-600/10 text-blue-500 border-blue-600/20' : isDark ? 'hover:bg-slate-800 border-transparent text-slate-300' : 'hover:bg-slate-100 border-transparent text-slate-600'}`}>
             Test Plan Generator
          </button>
          <button onClick={() => handleModuleSwitch('testcases')} className={`w-full flex items-center gap-3 p-3 text-sm font-semibold rounded-xl border transition-all ${activeModule === 'testcases' ? 'bg-indigo-600/10 text-indigo-500 border-indigo-600/20' : isDark ? 'hover:bg-slate-800 border-transparent text-slate-300' : 'hover:bg-slate-100 border-transparent text-slate-600'}`}>
             Smart Test Case Creation
          </button>
        </nav>

        {/* History Section */}
        <div className={`flex-1 overflow-y-auto flex flex-col mt-2 border-t ${isDark ? 'border-[#334155]' : 'border-slate-200'}`}>
          <div className="sticky top-0 p-4 pb-2 z-10 flex justify-between items-center bg-inherit">
             <p className="px-1 text-[10px] font-bold text-slate-400 uppercase tracking-widest">History</p>
             {history.length > 0 && <button onClick={() => setHistory([])} className="text-[10px] text-red-500 font-bold hover:underline">Clear All</button>}
          </div>
          <div className="px-2 pb-4 space-y-2">
            {history.length === 0 ? (
              <p className="text-xs text-center text-slate-500 italic mt-4">No logged history.</p>
            ) : (
              history.map(entry => (
                <div key={entry.id} className={`group flex flex-col p-3 rounded-xl border text-left cursor-pointer transition-all ${isDark ? 'bg-[#1e293b]/50 border-transparent hover:border-blue-500/30 hover:bg-slate-800' : 'bg-white border-transparent hover:border-blue-200 hover:shadow-sm'}`}>
                  <button onClick={() => loadHistoryItem(entry)} className="flex-1 text-left w-full">
                    <div className="font-bold text-xs truncate max-w-full text-slate-700 dark:text-slate-300">
                        {entry.activeModule === 'testcases' ? '📝 ' : '📋 '} {entry.title}
                    </div>
                    <div className="text-[10px] text-slate-400 mt-1">{entry.timestamp}</div>
                  </button>
                </div>
              ))
            )}
          </div>
        </div>
      </aside>

      <main className="flex-1 flex flex-col min-w-0 h-full overflow-hidden">
        <header className={`h-16 shrink-0 border-b flex items-center justify-between px-6 z-10 ${isDark ? 'bg-[#1e293b] border-[#334155]' : 'bg-white border-slate-200'}`}>
          <div className="flex items-center gap-2">
            <span className="text-slate-400 text-sm">Dashboard /</span>
            <span className="text-sm font-semibold">{activeModule === 'testplan' ? 'Test Plan Generator' : 'Smart Test Case Creation'}</span>
          </div>
          <div className="flex gap-2">
            <button onClick={() => setIsDark(!isDark)} className={`p-2 rounded-xl transition-colors ${isDark ? 'hover:bg-slate-800' : 'hover:bg-slate-100'} text-slate-500`}>
              {isDark ? '🌞' : '🌙'}
            </button>
            <button onClick={() => setShowSettings(true)} className={`p-2 rounded-xl transition-colors ${isDark ? 'hover:bg-slate-800' : 'hover:bg-slate-100'} text-slate-500 flex items-center gap-2`} title="Settings">
               ⚙️
            </button>
          </div>
        </header>

        <div className="p-4 flex-1 flex flex-col gap-4 overflow-hidden">
          <div className="grid grid-cols-2 gap-6 flex-1 min-h-0">
            {/* Input Column */}
            <div className="flex flex-col gap-3 min-h-0 h-full">
              <div className="flex flex-col flex-1 gap-3 min-h-0">
                <div>
                  <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2 block">Requirement Source</label>
                  <div className="flex gap-3">
                    <button onClick={() => setSourceMode('text')} className={`flex-1 p-2 text-center border-2 rounded-lg text-xs font-bold transition-all ${sourceMode === 'text' ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400' : (isDark ? 'border-[#334155] hover:border-slate-500' : 'border-slate-200 hover:border-slate-300')}`}>
                      Manual User Story
                    </button>
                    <button onClick={() => setSourceMode('jira')} className={`flex-1 p-2 text-center border-2 rounded-lg text-xs font-bold transition-all ${sourceMode === 'jira' ? 'border-blue-500 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400' : (isDark ? 'border-[#334155] hover:border-slate-500' : 'border-slate-200 hover:border-slate-300')}`}>
                      Jira Ticket ID
                    </button>
                    {activeModule === 'testcases' && (
                        <button onClick={() => setSourceMode('testplan')} className={`flex-1 p-2 text-center border-2 rounded-lg text-xs font-bold transition-all ${sourceMode === 'testplan' ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/20 text-indigo-600 dark:text-indigo-400' : (isDark ? 'border-[#334155] hover:border-slate-500' : 'border-slate-200 hover:border-slate-300')}`} title="Parse Test Cases from the previously generated Test Plan context.">
                            Test Plan Context
                        </button>
                    )}
                  </div>
                </div>

                {sourceMode === 'jira' && (
                  <div className="animate-in fade-in duration-300 shrink-0">
                    <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1 flex items-center justify-between">
                      Jira Issue Key / URL
                      {jiraFetchStatus && <span className="text-[10px] text-blue-500 animate-pulse">Fetching Context...</span>}
                    </label>
                    <div className="relative">
                      <input type="text" value={jiraKey} onChange={e => setJiraKey(e.target.value)} onBlur={fetchJiraTicket} className={`w-full p-2.5 pl-9 border rounded-lg shadow-sm text-xs focus:ring-2 focus:ring-blue-500 outline-none ${isDark ? 'bg-slate-800 border-[#334155]' : 'bg-white border-slate-200'}`} placeholder="e.g., https://.../browse/QA-123 or QA-123" />
                      <span className="absolute left-3 top-2.5 text-slate-400 text-xs">🔗</span>
                    </div>
                  </div>
                )}

                {sourceMode === 'testplan' && activeModule === 'testcases' && (
                  <div className="animate-in fade-in duration-300 flex-1 flex flex-col min-h-0 relative">
                    <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1">Generated Test Plan Payload Tracker</label>
                    <div className={`flex-1 p-4 border rounded-xl shadow-inner text-xs overflow-y-auto ${isDark ? 'bg-slate-800/80 border-indigo-500/30 text-slate-400' : 'bg-indigo-50 border-indigo-200 text-slate-600'}`}>
                        {generatedTestPlanRef || "No previous Test Plan tracked in session data. Generate one on the other tab."}
                    </div>
                  </div>
                )}

                <div className="flex-1 flex flex-col gap-2 min-h-0 relative">
                  <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400 shrink-0">
                    {sourceMode === 'jira' ? 'Jira User Stories Addendum' : 'Detailed Instructions / Prompts'}
                  </label>
                  <textarea value={inputText} onChange={e => setInputText(e.target.value)} className={`flex-1 p-4 border rounded-xl shadow-sm text-sm focus:ring-2 focus:ring-blue-500 outline-none resize-none overflow-y-auto leading-relaxed ${isDark ? 'bg-slate-800/50 border-[#334155]' : 'bg-white border-slate-200'}`} placeholder="Type detailed user story text, boundary edge-cases, or anti-hallucination rules..."></textarea>
                </div>
              </div>
            </div>

            {/* Output Column */}
            <div className="flex flex-col gap-2 min-h-0 h-full">
              <label className="text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center justify-between shrink-0">
                 {sourceMode === 'jira' && !generatedOutput && ticketContext ? 'Live Ticket Preview' : (activeModule === 'testcases' ? 'Jira SDET Output Pipeline' : 'Generated Output')}
                {isGenerating && (
                  <div className={`flex items-center gap-2 text-[10px] font-bold animate-pulse ${activeModule === 'testcases' ? 'text-indigo-500' : 'text-blue-500'}`}>
                    <span className={`w-1.5 h-1.5 rounded-full ${activeModule === 'testcases' ? 'bg-indigo-500' : 'bg-blue-500'}`}></span> SDET PROCESSING
                  </div>
                )}
              </label>
              <div className={`flex-1 border rounded-xl p-6 text-sm overflow-y-scroll whitespace-pre-wrap shadow-inner relative ${isDark ? 'bg-slate-800/30 border-[#334155]' : 'bg-white border-slate-200'}`}>
                {!generatedOutput && !ticketContext && (
                  <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-400 opacity-50 space-y-2">
                    <span className="text-3xl">{activeModule === 'testcases' ? '🧪' : '✨'}</span>
                    <p className="italic text-xs">Ready for generation pipeline...</p>
                  </div>
                )}
                <div className="relative z-10 leading-7 text-slate-700 dark:text-slate-300 markdown-body">
                  {generatedOutput || ticketContext}
                </div>
              </div>
            </div>
          </div>

          <div className={`py-4 px-6 shrink-0 flex justify-between items-center rounded-xl border shadow-sm ${isDark ? 'bg-[#1e293b] border-[#334155]' : 'bg-white border-slate-200'}`}>
             <div className="flex gap-4 text-[10px] font-bold uppercase tracking-tighter text-slate-400">
                <div className="flex items-center gap-1.5 px-2"><div className="w-1.5 h-1.5 rounded-full bg-green-500"></div> ENGINE {llmTestStatus==='success' ? 'CONNECTED' : 'IDLE'}</div>
                <div className="flex items-center gap-1.5 px-2 border-l border-slate-600/30"><div className="w-1.5 h-1.5 rounded-full bg-blue-500"></div> SOURCE: {sourceMode.toUpperCase()} BOUND</div>
                {activeModule === 'testcases' && (
                    <div className="flex items-center gap-1.5 px-2 border-l border-slate-600/30"><div className="w-1.5 h-1.5 rounded-full bg-indigo-500"></div> ANTI-HALLUCINATION ENFORCED</div>
                )}
             </div>
             <div className="flex gap-3">
                <button onClick={executeAIRequest} disabled={isGenerating} className={`px-8 py-2.5 text-white text-sm rounded-lg font-bold active:scale-95 transition-all outline-none flex items-center gap-2 shadow-lg disabled:opacity-50 ${activeModule === 'testcases' ? 'bg-indigo-600 hover:bg-indigo-700 shadow-indigo-500/20' : 'bg-blue-600 hover:bg-blue-700 shadow-blue-500/20'}`}>
                  {activeModule === 'testcases' ? 'Generate Target Cases' : 'Generate Test Plan'}
                </button>
                <div className="flex drop-shadow-sm border rounded-lg overflow-hidden border-slate-200 dark:border-[#334155]">
                    {activeModule === 'testcases' && generatedOutput && (
                        <button onClick={() => setShowPreviewModal(true)} className={`px-4 py-2 text-xs font-bold transition-all flex items-center gap-2 border-r ${isDark ? 'border-[#334155] hover:bg-emerald-900/40 text-emerald-400' : 'border-slate-200 hover:bg-emerald-50 text-emerald-600'}`} title="Preview cleanly in a full-screen window">
                            Preview
                        </button>
                    )}
                    {activeModule === 'testcases' && (
                        <button onClick={() => downloadXLSX(null)} className={`px-4 py-2 text-xs font-bold transition-all flex items-center gap-2 border-r ${isDark ? 'border-[#334155] hover:bg-indigo-900/40 text-indigo-300' : 'border-slate-200 hover:bg-indigo-50 text-indigo-700'}`} title="Download formatted dataset into XLSX payload">
                            Download XLSX
                        </button>
                    )}
                    <button onClick={() => downloadMarkdown(null)} className={`px-4 py-2 text-xs font-bold transition-all flex items-center gap-2 ${isDark ? 'hover:bg-slate-800' : 'hover:bg-slate-50'}`} title="Download exact Markdown text block">
                        Download MD
                    </button>
                </div>
             </div>
          </div>
        </div>
      </main>

      {/* Settings Modal */}
      {showSettings && (
        <div className="fixed inset-0 bg-slate-900/80 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className={`rounded-2xl p-6 w-full max-w-lg shadow-2xl border max-h-[85vh] overflow-y-auto ${isDark ? 'bg-[#1e293b] border-[#334155]' : 'bg-white border-slate-200'}`}>
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-xl font-bold">Settings</h2>
              <button onClick={() => setShowSettings(false)} className={`p-1.5 rounded-full ${isDark ? 'hover:bg-slate-800' : 'hover:bg-slate-100'}`}>✕</button>
            </div>

            <div className={`p-5 rounded-xl mb-5 space-y-3 border ${isDark ? 'bg-slate-900/50 border-slate-800' : 'bg-slate-50 border-slate-100'}`}>
              <h3 className="font-bold text-xs uppercase text-blue-500">LLM Engine</h3>
              <select value={llmConfig.provider} onChange={e => setLlmConfig({...llmConfig, provider: e.target.value})} className={`w-full p-2.5 rounded-lg text-sm border ${isDark ? 'bg-slate-800 border-[#334155]' : 'bg-white border-slate-200'}`}>
                <option value="openai">OpenAI</option>
                <option value="groq">GROQ</option>
                <option value="ollama">Ollama (Local)</option>
                <option value="grok">Grok</option>
              </select>
              <div className="grid grid-cols-2 gap-3">
                 <input type="text" placeholder="Model Name" value={llmConfig.modelName} onChange={e => setLlmConfig({...llmConfig, modelName: e.target.value})} className={`w-full p-2.5 rounded-lg text-sm border ${isDark ? 'bg-slate-800 border-[#334155]' : 'bg-white border-slate-200'}`} />
                 <input type="text" placeholder="API URL (optional)" value={llmConfig.apiUrl} onChange={e => setLlmConfig({...llmConfig, apiUrl: e.target.value})} className={`w-full p-2.5 rounded-lg text-sm border ${isDark ? 'bg-slate-800 border-[#334155]' : 'bg-white border-slate-200'}`} />
              </div>
              <input type="password" placeholder="API Key" value={llmConfig.apiKey} onChange={e => setLlmConfig({...llmConfig, apiKey: e.target.value})} className={`w-full p-2.5 rounded-lg text-sm border ${isDark ? 'bg-slate-800 border-[#334155]' : 'bg-white border-slate-200'}`} />
              <button onClick={() => testConnection('llm')} className={`w-full py-2.5 text-xs font-bold rounded-lg border transition-all ${isDark ? 'bg-slate-800 border-[#334155] hover:border-blue-500' : 'bg-white border-slate-200 hover:border-blue-500'}`}>
                {llmTestStatus === 'checking' ? 'Checking...' : llmTestStatus === 'success' ? 'Connected ✓' : llmTestStatus === 'error' ? 'Connection Failed' : 'Test LLM Connection'}
              </button>
            </div>

            <div className={`p-5 rounded-xl space-y-3 border ${isDark ? 'bg-slate-900/50 border-slate-800' : 'bg-slate-50 border-slate-100'}`}>
              <h3 className="font-bold text-xs uppercase text-indigo-500">Jira/ADO Source</h3>
              <select value={sourceConfig.provider} onChange={e => setSourceConfig({...sourceConfig, provider: e.target.value})} className={`w-full p-2.5 rounded-lg text-sm border ${isDark ? 'bg-slate-800 border-[#334155]' : 'bg-white border-slate-200'}`}>
                <option value="jira">Jira Cloud</option>
                <option value="ado">Azure DevOps (ADO)</option>
              </select>
              <input type="text" placeholder="Instance URL (e.g. dev.atlassian.net)" value={sourceConfig.domainUrl} onChange={e => setSourceConfig({...sourceConfig, domainUrl: e.target.value})} className={`w-full p-2.5 rounded-lg text-sm border ${isDark ? 'bg-slate-800 border-[#334155]' : 'bg-white border-slate-200'}`} />
              <div className="grid grid-cols-2 gap-3">
                 <input type="text" placeholder="Email Account" value={sourceConfig.email} onChange={e => setSourceConfig({...sourceConfig, email: e.target.value})} className={`w-full p-2.5 rounded-lg text-sm border ${isDark ? 'bg-slate-800 border-[#334155]' : 'bg-white border-slate-200'}`} />
                 <input type="password" placeholder="API Token/PAT" value={sourceConfig.apiToken} onChange={e => setSourceConfig({...sourceConfig, apiToken: e.target.value})} className={`w-full p-2.5 rounded-lg text-sm border ${isDark ? 'bg-slate-800 border-[#334155]' : 'bg-white border-slate-200'}`} />
              </div>
              <button onClick={() => testConnection('jira')} className={`w-full py-2.5 text-xs font-bold rounded-lg border transition-all ${isDark ? 'bg-slate-800 border-[#334155] hover:border-indigo-500' : 'bg-white border-slate-200 hover:border-indigo-500'}`}>
                {jiraTestStatus === 'checking' ? 'Checking...' : jiraTestStatus === 'success' ? 'Connected ✓' : jiraTestStatus === 'error' ? 'Connection Failed' : 'Test Source Connection'}
              </button>
            </div>

            <button onClick={() => setShowSettings(false)} className="w-full mt-5 py-3 bg-blue-600 text-white font-bold text-sm rounded-xl shadow-md hover:bg-blue-700">Close Options</button>
          </div>
        </div>
      )}

      {/* Preview Modal for Smart Test Cases */}
      {showPreviewModal && (
        <div onClick={() => setShowPreviewModal(false)} className="fixed inset-0 bg-slate-900/80 backdrop-blur-sm flex items-center justify-center z-50 p-6">
          <div onClick={(e) => e.stopPropagation()} className={`rounded-2xl flex flex-col w-full max-w-7xl h-[90vh] shadow-2xl border ${isDark ? 'bg-[#1e293b] border-[#334155]' : 'bg-white border-slate-200'}`}>
            <div className={`flex justify-between items-center p-6 border-b ${isDark ? 'border-slate-700/50' : 'border-slate-200'}`}>
              <h2 className="text-xl font-bold flex items-center gap-2">
                 <span className="text-2xl">📝</span> Smart Test Case Preview
              </h2>
              <button onClick={() => setShowPreviewModal(false)} className={`p-2 rounded-full transition-colors ${isDark ? 'hover:bg-slate-800' : 'hover:bg-slate-100'} text-slate-400`}>✕</button>
            </div>
            
            <div className={`flex-1 p-8 overflow-y-scroll leading-relaxed text-[15px] whitespace-pre-wrap ${isDark ? 'text-slate-200' : 'text-slate-800'}`}>
               {parseMarkdownToTable(generatedOutput)}
            </div>

            <div className={`p-5 flex justify-end border-t ${isDark ? 'border-slate-700/50' : 'border-slate-200'}`}>
               <button onClick={() => setShowPreviewModal(false)} className="px-6 py-2.5 bg-slate-600 text-white font-bold rounded-xl shadow hover:bg-slate-700 transition-colors">
                 Close View
               </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
